---
title: "STA 137 HW5"
author: "Cheng Liu"
date: "3/2/2021"
output: pdf_document
---
4.
```{r}
setwd("D:/r scripts")
mdata = read.csv("GlobTempNASA_2020.csv")

plot.ts(mdata$Value, xlab = "year", ylab = "temps")
x = unlist(mdata$Value)
y = diff(x,1)
plot.ts(y, xlab = "year", ylab = "first difference temps")
acf(y)
pacf(y)
```

```{r}
library(astsa)

AICc<-matrix(0,4,4)
for(i in 1:4){
  for(j in 1:4){
    AICc[i,j]=sarima(x,p=i-1,d=1,q=j-1,details=FALSE)$AICc
  }
}
AICc

bestmodel = sarima(x,p=1,d=1,q=1,details=FALSE)
bestmodel
model = arima(x,order=c(1,1,1))
acf(model$residuals)

bestmodel$ttable
```
b.Based on the AICC value, we will choose ARIMA(1,1,1) model with the second smallest AICC value(-0.499) and fewer parameters. Please see above for the btained estimated value and standard error. The residuals can be described as white noise.

```{r}
library(forecast)
model <-auto.arima(x, stepwise=F, approximation=F, ic="aicc")
model
n <-length(x)
plot.ts(x)
lines(1:n, model$fitted, col = "blue")
legend("top", legend =c("true","fitted"), lty=c(1, 1), col =c("black","blue"))
```

```{r}
xnew = x[1:(n-5)]
xlast = x[(n-4):n]
newmodel = arima(xnew,order = c(1,1,1))
h = 5
m = n-h
focast = predict(newmodel,n.ahead = h)
upper = focast$pred+1.96*focast$se
lower = focast$pred-1.96*focast$se

plot.ts(xnew, xlim = c(0,n),xlab = "x")
polygon(x = c(m+1:h,m+h:1), y = c(upper,rev(lower)), col = "lightgreen", border = NA)
lines(x=m+(1:h), y= focast$pred,col = "black")
lines(x=m+(1:h), y= xlast,col = "blue")
legend("top", legend =c("true","fitted"), lty=c(1, 1), col =c("black","blue"))
```
c. The predicted value is in the 95% confidence interval, but the trend for the estimated part should be downwards rather than upwards.






























